SubbieWeb/Controllers/SplashController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Utilitarios;
using Datos;
using LogicaDeNegocios;
using SubbieWeb.Controllers.Servicios;
using Datos;
namespace SubbieWeb.Controllers

{
    public class SplashController : Controller
    {
       
       
        public ActionResult Login()
        {
        
            return View();
        }
        [HttpPost]
        public ActionResult Login(string correo,string password)
        {
            try {

                UUsuarios user = new UUsuarios();
                using (var db = new DBMapeo())
                {

                    user = db.usuarios.Where(x => x.Correo.Equals(correo) && x.Password.Equals(password)).FirstOrDefault();
                    var comprobar = user.UsuarioNuevo;

                    if (user == null)
                    {
                        return View();
                    }
                    Session["User"] = user;
                    if (comprobar == false)
                    {
                        return RedirectToAction("InfoUsuarios", "Home");
                        
                    }
                   
                }
                return RedirectToAction("Index","Home");

            }
            catch (Exception ex) {
                ViewBag.Error = ex.Message;
                return View();
            
            }
           
   

        }
       
        public ActionResult Registrer()
        {

            return View();
        }
        

    }
}

SubbieWeb/Views/Shared/_LayaoutLoginRegistrer.cshtml
<!DOCTYPE html>
<html>
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.title - Subbie</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar ">
        <div class="">
            <div class="">
                <div style="font-size: 40px; margin-top: -2px; margin-left: 40px; background-color: #10FFCE; width: 40px; height: 40px; border-radius: 10px; text-align: center; padding-top: -5px;"><div style=" position:absolute; top:-5px; left:50px;"> S</div></div>
                <div style=" color: #10FFCE; font-size: 30px; float: left; position: absolute; top: 0; left: 90px;">ubbie</div>
                <a href=~/Views/Splash/Registrer" style="">@Html.ActionLink("Login", "login", "Splash", new { @class = "btnlogin" }))</a>
                <a href=~/Views/Splash/Registrer" style="">@Html.ActionLink("registrar", "Registrer", "Splash", new { @class = "btnregister" }))</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Login", "Login", "Splash")</li>
                    <li>@Html.ActionLink("Registrer", "Registrer", "Splash")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="texto-bienvenida">
        <br />
        Bienvenidos, juntos contribuiremos a la revolución de compras online.
        <br />
        <input type="submit" class="btn btn-success" value="Leer más">
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>

</html>

SubbieWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="~/Content/Site.css" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.title Home</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <a href="https://www.freepik.com" title="Freepik"></a><a href="https://www.flaticon.es/" title="Flaticon"></a>
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div id="contenedor_barra" class="barra-lateral d-flex align-items-start flex-column bd-highlight mb-3">
        <div class="logoS p-2 bd-highlight">
            <h4 style="color: #10ffce">ubbie</h4>
        </div>
        <div class="menu p-2 bd-highlight">
            <ul class="nav navbar-nav" style="font-size: 20px">
                <li><img src="~/img/001-home.png" width="20" height="20" /> @Html.ActionLink("Inicio", "Index", "Home", new { @class = "links" })</li>
                <br />
                <li><img src="~/img/002-publication.png" width="20" height="20" />@Html.ActionLink("Publicar", "Publicar", "Home", new { @class = "links" })</li>
                <br>
                <li><img src="~/img/003-box.png" width="20" height="20" />@Html.ActionLink("Productos", "Contact", "Home", new { @class = "links" })</li>
                <br />
                <li><img src="~/img/004-chat.png" width="20" height="20" />@Html.ActionLink("Chat", "Chat", "Home", new { @class = "links" })</li>
                <br />
                <li><img src="~/img/005-frequentist-statistics.png" width="20" height="20" />@Html.ActionLink("Estadisticas", "Estadisticas", "Home", new { @class = "links" })</li>
            </ul>
        </div>
        <div class="nav navbar-nav mt-auto p-2 bd-highlight" style="font-size: 20px">
            <li><img src="~/img/006-emergency-exit.png" width="20" height="20" />@Html.ActionLink("Salir", "Contact", "Home", new { @class = "links" })</li>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts",required: false)
</body>
</html>